FROM node:20-alpine as dependencies

# rewquired for installing
RUN apk add --no-cache git
RUN apk add --no-cache openssh-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm i

# Build stage
FROM node:20-alpine AS build

WORKDIR /usr/src/app

# Copy dependencies, package.json, app code
COPY --from=dependencies ./usr/src/app/node_modules ./node_modules
COPY --from=dependencies ./usr/src/app/package*.json ./
COPY . .

# Build the React application with build arguments
ARG VITE_TITLE
ARG VITE_API_BASE
ARG VITE_ASSET_BASE
ARG VITE_MAP_KEY

ENV VITE_TITLE=$VITE_TITLE
ENV VITE_API_BASE=$VITE_API_BASE
ENV VITE_ASSET_BASE=$VITE_ASSET_BASE
ENV VITE_MAP_KEY=$VITE_MAP_KEY

RUN npm run build

# Use the official Nginx image to serve the build
FROM nginx:stable-alpine3.19-slim

# Copy the build output to the Nginx html directory
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
COPY --from=build /usr/src/app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]