server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache Static assets for 6 months
    location ~* \.(gltf|glb|jpg|jpeg|png|gif|webp|svg|woff|woff2|ttf|otf|eot|hdr|css|js|html)$ {
        expires 6M;
        add_header Cache-Control "public";
    }
}